
fluent-bit:
  config:
    outputs: |
      [OUTPUT]
          Name loki
          Match *
          Host loki-distributed-gateway.observability.svc.cluster.local
          Port 80
          Labels job=fluent-bit
