
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dayashimoga/sre-observability-lab-enhanced-ag.git
    targetRevision: HEAD
    path: helm-charts/core
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
