
apiVersion: v2
name: opentelemetry-collector
description: Wrapper for opentelemetry-collector
type: application
version: 1.0.0
appVersion: "0.90.0"
dependencies:
  - name: opentelemetry-collector
    version: 0.76.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
