
tempo:
  tempo:
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: minio.core.svc.cluster.local:9000
          access_key: admin
          secret_key: password123
          insecure: true
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
